### ISSUE TITLE
Setup firebase and send notifications to mobile app from mediator

### ISSUE THREAD

**Issue by sairanjit** [credebl/adeya-wallet#106]
## Summary
- Setup Firebase and send notifications to the mobile app from the mediator

## Tasks

- [x] Setup the Firebase account for the server
- [x] Add the firebase config in the mediator agent
- [x] Send push notifications for the registered devices
- [x] Send notifications only if device is inactive

**Comment by sairanjit** [comment]
https://github.com/credebl/mediator-agent/pull/1
