### ISSUE TITLE
Add android config in wallet

### ISSUE THREAD

**Issue by poonam-ghewande** [credebl/adeya-wallet#88]
## Tasks

- [x] Add firebase in android 
- [x] Add push notification module 
- [x] add push notification toggle setting menu
- [x] Test push notification for android

**Comment by poonam-ghewande** [comment]
Completed Android firebase configuration for notifications .
