### ISSUE TITLE
Project Setup for SDK

### ISSUE THREAD

**Issue by sairanjit** [credebl/adeya-wallet#95]
## Summary
- Create a React Native SDK project 

## Tasks

- [x] Create a new repository for SDK
- [x] Create a new react native library with [create-react-native-library](https://github.com/callstack/react-native-builder-bob)
- [x] Setup Linting, Prettier and Typescript
